// <auto-generated />
using System;
using Curso_Entity_Framework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Curso_Entity_Framework.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20231207195251_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Curso_Entity_Framework.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("97c9f346-b27c-4d0f-98ba-ae0b769604b6"),
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("97c9f346-b27c-4d0f-98ba-ae0b769714b6"),
                            Nombre = "Actividades personales",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("Curso_Entity_Framework.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("abd281ac-d1fb-4fb6-8c4e-39a82c6370ef"),
                            CategoriaId = new Guid("97c9f346-b27c-4d0f-98ba-ae0b769604b6"),
                            FechaCreacion = new DateTime(2023, 12, 7, 13, 52, 51, 40, DateTimeKind.Local).AddTicks(4412),
                            PrioridadTarea = 1,
                            titulo = "Pago de telefono fijo"
                        },
                        new
                        {
                            TareaId = new Guid("abd281ac-d1fb-4fb6-8c4e-39a82c63701f"),
                            CategoriaId = new Guid("97c9f346-b27c-4d0f-98ba-ae0b769714b6"),
                            FechaCreacion = new DateTime(2023, 12, 7, 13, 52, 51, 40, DateTimeKind.Local).AddTicks(4428),
                            PrioridadTarea = 2,
                            titulo = "Ver los cursos de Platzi"
                        });
                });

            modelBuilder.Entity("Curso_Entity_Framework.Models.Tarea", b =>
                {
                    b.HasOne("Curso_Entity_Framework.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Curso_Entity_Framework.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
